[exchange]
username = "drab.dustin@athenamfg.com"
password = "temp123"
server   = "outlook.office365.com"
cc       = "quotes@athenamfg.com"

[company]
name         = "Athena Manufacturing"
sender_name  = "Dustin Drab"
sender_email = "drab.dustin@athenamfg.com"
sender_title = "Estimating Manager"
sender_phone = "737-787-7211"

[app]
subject_prefix = "[RFQ-]"
